# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'CommitList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cherry
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftLint'

  target 'CommitListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommitListUITests' do
    # Pods for testing
  end

end